# Generated by Django 5.0.6 on 2024-05-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_menuitem_menu_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price_raw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
