# Generated by Django 5.0.6 on 2024-05-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_restaurant_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
