# Generated by Django 5.0.6 on 2024-05-31 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_menuitem_price_alter_menuitem_price_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='data.restaurant'),
        ),
    ]
