# Generated by Django 5.0.6 on 2024-05-31 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_rating_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucard',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_cards', to='data.restaurant'),
        ),
        migrations.AlterField(
            model_name='openingtime',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_times', to='data.restaurant'),
        ),
        migrations.AlterField(
            model_name='property',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='data.restaurant'),
        ),
        migrations.AlterField(
            model_name='reviewtag',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='data.restaurant'),
        ),
        migrations.AlterField(
            model_name='service',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='data.restaurant'),
        ),
        migrations.AlterField(
            model_name='utilization',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizations', to='data.restaurant'),
        ),
    ]
