# Generated by Django 5.0.6 on 2024-05-31 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_menuitem_menu_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data.menucard'),
        ),
        migrations.AlterField(
            model_name='menuitemingredient',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='data.menuitem'),
        ),
    ]
