# Generated by Django 5.0.6 on 2024-05-31 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_rating_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtag',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tags', to='data.restaurant'),
        ),
    ]
